# -*- coding: utf-8 -*-
"""PeerGradedAssignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rooBUzwwe2NspxBuvIm6cO42kgC42SKW
"""

# Peer Graded Assignment

"""# Peer Graded Assignment

## Introduction

In this notebook, we are going to learn about Data Science Tools and Data Science Languages

## Data Science Languages

- Python
- R
- Julia
- Scala
- SQL
- SAS

## Data Science Libraries

- NumPy
- pandas
- Matplotlib
- Seaborn
- scikit-learn
- TensorFlow
- PyTorch
- statsmodels
- XGBoost

## Data Science Tools

| Tool Name         | Description                                           |
|-------------------|-------------------------------------------------------|
| Python            | A versatile programming language for data analysis.   |
| R                 | A statistical computing and graphics language.        |
| Jupyter Notebook  | An interactive notebook for data analysis and code.   |
| NumPy             | A library for numerical and array operations in Python. |
| pandas            | A library for data manipulation and analysis in Python. |
| Matplotlib        | A plotting library for creating data visualizations.  |
| scikit-learn      | A machine learning library for Python.               |
| TensorFlow        | An open-source machine learning framework by Google.  |
| PyTorch           | An open-source deep learning framework by Facebook.  |
"""



"""## Arithmetic Expression Examples

In this section, we will explore various arithmetic expressions and operations using Python. Arithmetic expressions involve mathematical operations such as addition, subtraction, multiplication, and division. Below are some examples:

### Addition

To add two numbers in Python, use the `+` operator:

```python
result = 5 + 3
print(result)  # Output: 8
```

Subtraction
To subtract one number from another, use the - operator:
```
result = 10 - 4
print(result)  # Output: 6
```
"""

# Multiply and add numbers
num1 = 5
num2 = 3

# Multiply
result_multiply = num1 * num2
print("Multiplication result:", result_multiply)

# Add
result_add = num1 + num2
print("Addition result:", result_add)

# Convert minutes to hours
minutes = 120

# Calculate hours
hours = minutes / 60

# Display the result
print(f"{minutes} minutes is equal to {hours} hours.")

"""## Objectives

- Learn about data analysis techniques.
- Explore data visualization with Matplotlib.
- Understand how to manipulate data using pandas.
- Practice writing Python code for data analysis.

**Author:** Vishal Jha
"""